### ISSUE TITLE
Include some kind of EventSystem/EventManager

### ISSUE THREAD

**Issue by Gronis** [Gronis/OpenEcs#1]
Right now, the only way of communicating between systems is by assigning different components. Doing this by using Events and listen to these events might be useful.

EDIT: This will not be implemented. Let me describe why:
- In the case of a general solution, just implementing the Listener pattern for systems is an easy thing to do. In the end, it would look something like this. This approach should cover 9 out of 10 senarious where you might consider using some kind of event system:

``` cpp
class CollisionEvent{ Entity entityA; Entity entityB; };
class CollisionSystem : System, EventListener<CollisionEvent> {
     public:
         void handle(CollisionEvent& ev) override {
             doSomething(ev.entityA, ev.entityB);
         }
  }
```
- In the case of specific entity behaviour, for example the player character, (eg behaviour that would be located in script files when working with a game engine), consider the following approach. 

Create an (Event) component which holds a function, that is executed when something happens

``` cpp
struct OnCollision : Property<std::function<void(Entity&)>>{};
```

Then add entity specific behavior for a specific event for that entity

``` cpp
entity.add<OnCollision>([&](Entity& e) {
   if(e.is<Harmful>()){ //<-- Harmful is an entity alias for a damaging object
      entity.get<Health>() -= e.get<Damage>();
   }
});
```

Then when the event occurs in the code, check for event component:

``` cpp
//Assume e1 and e2 is colliding
if(e1.has<OnCollision>()) e1.get<OnCollision>()(e2);
if(e2.has<OnCollision>()) e2.get<OnCollision>()(e1);
```

In case you have another way of implementing events, or argue why an event manager should be included in OpenEcs, feel free to comment below.

**Comment by LeviTaule** [comment]
What about `Command`s and a `CommandManager`? Wouldn't it be a nice and flexible way of communication between components?

**Comment by Gronis** [comment]
Could you please describe in more detail how you mean? I'm open to suggestions. 

I have looked at different approaches, but cannot find a solution I like. Perhaps it's a problem that should not be part of the OpenECS but rather an external library, or perhaps some kind of extension for those that do wish to use a build in Event/Message/Command system.

**Comment by LeviTaule** [comment]
In my ECS I was mainly concerned about how do I make an elegant and flexible input handling. I am not sure how this would scale though.
Here's a minimal example

_main loop_

``` cpp
while(window.isOpen())
{
    sf::Event event;
    while(window.pollEvent(event))
    {
        input_system.execute(event);
    }
    kinematics_system.execute();
    command_system.execute();
    render_system.execute();
    window.display();
}
```

_InputComponent_ holds a list of function callbacks returning `shared_ptr<Command>` you can set. This is how you can use it

``` cpp
RenderComponent render_component(u_drawable);
RenderSystem render_system(render_component, window);

KinematicsComponent kinematics_component(*shape);
KinematicsSystem kinematics_system(kinematics_component, render_component.get_transform());

CommandComponent command_component;
CommandSystem command_system(command_component);

InputComponent input_component;
InputSystem input_system(input_component, command_component);

auto fun = [&kinematics_component, &render_component](const sf::Event::MouseMoveEvent & mouse_move) -> std::shared_ptr<Command>
{
    if(!sf::Keyboard::isKeyPressed(sf::Keyboard::A))
    {
        auto command = std::make_shared<MoveCommand>(kinematics_component, render_component, sf::Vector2f(mouse_move.x, mouse_move.y));
        return std::static_pointer_cast<Command>(command);
    }
    else
    {
        return std::static_pointer_cast<Command>(std::make_shared<EmptyCommand>());
    }
};
input_component.set_on_mouse_moved(fun);
```

`Command` example

``` cpp
struct CloseCommand: public Command
{
    CloseCommand(sf::Window & window) : window(window) {};
    virtual ~CloseCommand() = default;

    virtual void execute() override
    {
        window.close();
    }

    sf::Window & window;
};
```

_InputSystem_ simply returns the shared_ptr to Command

``` cpp
void InputSystem::execute(const sf::Event & event) const
{
    switch(event.type)
    {
    case sf::Event::Closed:
        if(component.isset_on_close)
        {
            command_component.push_command(component.on_close());
        }

        break;
/// ...
```

_CommandSystem_ simply executes all the `Command`s in the `deque`.

As I have mentioned, I am not sure how this would scale, I am only using this for the input handling and the rest I am simply passing the relevant info to the systems (as you can see in the `KinematicsSystem`). Maybe, as you write, this is too implementation-specific and should be handled outside of the ECS.

**Comment by Gronis** [comment]
As you say, your implementation might be too dependent with the domain. One solution I had in mind would be a much more simplified version of what you do. By Introducing Event components, it is easy to add custom behaviour to specific entities.

``` c++
struct OnCollision : Property<std::function<void(Entity&)>>{};

...

entity.add<OnCollision>([&](Entity& e) {
   if(e.is<Harmful>()){ //<-- Harmful is an entity alias for a damaging object
      entity.get<Health>() -= e.get<Damage>();
   }
});
```

Then in the CollisionSystem update function:

``` c++
//Assume e1 and e2 is colliding
if(e1.has<OnCollision>()) e1.get<OnCollision>()(e2);
if(e2.has<OnCollision>()) e2.get<OnCollision>()(e1);
```

However this only solves behaviour that is specific to specific entities. In a general case, for example a system that counts the amount of damage dealt to every character, the above solution is very superfluous, and a traditional listener pattern between systems might be better.

Anyway, if specific behaviour is needed, no further implementation is needed, as "OnCollision" is just another component with an std::function. If a generic/not entity specific solution is needed, as in the case of a damage counter for all characters, it is probably easier to let the users of this library implement their own solution.

**Comment by cemper** [comment]
I do not think you should add function components to entities. The conventional wisdom is that in an ECS, all behavior should be kept in systems, not in the components. Rather, IMO you should add a second (optional) interface for systems or other objects to implement.

```
 class CollisionSystem : System, EventListener<CollisionEvent> {
     public:
         void handle(CollisionEvent& ev) override {
             doSomething(ev->entityA, ev->entityB);
         }
  }
```

However, there is actually no need to make this part of the ECS itself -- it can be developed as an independent library and then potentially required by OpenEcs to allow for OpenEcs to trigger events on entity creation or removal.

**Comment by Gronis** [comment]
This is exactly what I meant. These things can be handled by a separate library or a user defined library. It does not need to be included.

The idea behind EventComponents was if only a few or maybe only one entity needed that feedback (e.g player character or whatever), that kind of event is something that people might consider putting into a script component, and then add that script to that entity. This is a way of doing that without using a script. 

But, in 9 out of 10 cases, your approach with Systems as EventListeners is the way to go.
