### ISSUE TITLE
Component Inheritance

### ISSUE THREAD

**Issue by waldnercharles** [Gronis/OpenEcs#10]
Currently OpenEcs does not take into account inheritance when querying components.

Resulting in this behavior:

``` c++
struct Renderable {
  virtual void Draw() = 0;
};

struct Shape : public Renderable {
  virtual void Draw() { ... }
};

int main() {
  EntityManager entities;
  Entity entity = entities.create();
  entity.add<Shape>();
  entity.has<Renderable>(); // returns false
}
```

Is there any way to allow for OpenEcs to handle this gracefully?

**Comment by Gronis** [comment]
Using inheritance are not supported at the moment. From the definition of entity component system, a component should just be a POD (plain old data) which is just structs of data (no behaviour).

I must say I wonder how the behaviour would be defined if this was supported. Let's say we have 2 classes inheriting Renderable:

``` c++
struct Shape : public Renderable {
  virtual void Draw() { ... }
};

struct Sprite : public Renderable {
  virtual void Draw() { ... }
};

int main() {
  EntityManager entities;
  Entity entity = entities.create();
  entity.add<Shape>();
  entity.add<Sprite>();
  entity.get<Renderable>(); // should this return the Shape or Sprite?
}
```

For the purpose you are doing, I think it is better to use the EntityAlias and define the draw function there. Or create separate systems and let each and every one implement different way of rendering a shape. I'm not really sure what you have in mind, but I think adding support for inheritance on components might not be the optimal solution, unless we can define a proper behaviour for things like the example I gave above.

**Comment by waldnercharles** [comment]
That's a good point. I didn't take that into account. Closing.
