### ISSUE TITLE
Cannot include ecs.h into multiple files.

### ISSUE THREAD

**Issue by waldnercharles** [Gronis/OpenEcs#7]
After trying to include ecs.h into multiple files, I get a multiple definitions exception.

It's possible to get past the errors by inlining all of the methods gcc complains about.

**Comment by Gronis** [comment]
Hi waldnercharles and thanks for reporting an issue :)

However, I cannot reproduce the error you mention (I can successfully include it into different files). What definitions are defined multiple times? What kind of build system are you using? Have you enabled c++11 with -std=c++11?

According to <a href="http://stackoverflow.com/questions/27586100/multiple-definition-exception-in-c">stackoverflow</a> this error is a result from not using a header guard, which should not be a problem.

**Comment by waldnercharles** [comment]
Just want to be clear, the ecs.h I'm referring to is in single_include, not include/ecs.h.
You are unable to reproduce the problem with the single_include file?

Here is a sample of what reproduces the problem on my machine.

``` c++
// main.cpp
#include "single_include/ecs.h"
#include "world.h"
int main() {
  // ..
}
```

``` c++
// world.h
#pragma once // This could also be an ifndef
#include "single_include/ecs.h"

class World {
 public:
  World();
  void Begin();
 private:
  ecs::EntityManager entities;
  ecs::SystemManager systems;
}
```

``` c++
// world.cpp
#include "world.h"
World::World() : systems(entities) { }
void World::Begin() {
  // ...
}
```

I'm using cmake and am running gcc with the flag -std=c++11

**Comment by Gronis** [comment]
Ok, now I see that the problem is due to linkage, we include ecs from two different cpp files. This should be solvable by using inline. I'm trying it out right now and hopefully, it should solve the linkage problem.

**Comment by Gronis** [comment]
Try out this version, I basically added inline where all the definitions where duplicated. Not sure if this introduces other bugs, but it passes all the tests. Try it out and see it it's working for you :) 

Edit: Just to be clear, it now works for your example.

**Comment by waldnercharles** [comment]
It looks like changing all of the definitions to inline solves the problem.
Thanks for all the hard work. Looking forward to using this library.

**Comment by Gronis** [comment]
Wonderfull! It's nice to see someone using it :) I haven't had the time to use it much myself. Let me know if you find any more issues!
